{% set name = "jsondiff" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2795844ef075ec8a2b8d385c4d59f5ea48b08e7180fce3cb2787be0db00b1fb4

build:
  number: 1
  noarch: python
  entry_points:
    - jdiff=jsondiff.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - jsondiff
  commands:
    - jdiff --help
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ZoomerAnalytics/jsondiff
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Diff JSON and JSON-like structures in Python

extra:
  recipe-maintainers:
    - mariusvniekerk
